-- V4__add_soft_delete.sql
ALTER TABLE books ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE book_loans ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
